title: disclose.io
description: Driving safety, simplicity, and standardization in vulnerability disclosure.
url: "https://disclose.io"
baseurl: ""
logo: /assets/img/logo.png
google_analytics: "UA-35052704-20"
