name: validate-json

on: [pull_request]

jobs:
  validate_json_fix_job:
    runs-on: ubuntu-latest
    name: validate-json job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: validate-json action step
      uses: ./.github/actions/validate-json
